import { pgTable, text, timestamp, uuid, index, unique, customType } from "drizzle-orm/pg-core";
import { workspaces } from "../../shared/schema/workspaces";
import { leads } from "./leads";

/** Postgres BYTEA column type for Drizzle (not built-in) */
const bytea = customType<{ data: Buffer; notNull: false; default: false }>({
  dataType() {
    return "bytea";
  },
});

/**
 * Pitch pages: AI-generated personalised proposal pages for leads.
 * Each page is served publicly via /api/pitch/[slug].
 * Optionally stores a PDF version in pdf_bytes.
 */
export const pitchPages = pgTable(
  "pitch_pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => leads.id, { onDelete: "cascade" }),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    html: text("html").notNull(),
    urlSlug: text("url_slug").notNull(),
    modelUsed: text("model_used"),
    costCents: text("cost_cents").default("0"),
    /** Pre-rendered PDF bytes for this proposal (generated by @react-pdf/renderer) */
    pdfBytes: bytea("pdf_bytes"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    unique("uq_pitch_pages_slug").on(table.urlSlug),
    index("idx_pitch_pages_lead").on(table.leadId),
    index("idx_pitch_pages_workspace").on(table.workspaceId),
  ],
);
