/**
 * Seed data for local development.
 * Used by:
 * - packages/db/seed.ts to populate the database
 * - Components as fallback when DB has no data (dev convenience)
 */

export const SEED_LEADS = [
  {
    name: "Active Ability Support",
    googlePlaceId: "ChIJ_seed_active_ability",
    category: "NDIS Provider",
    address: "123 Barkly St",
    suburb: "Footscray",
    state: "VIC",
    postcode: "3011",
    country: "AU",
    lat: -37.800,
    lng: 144.899,
    phone: "03 9012 3456",
    website: "activeability.com.au",
    email: "info@activeability.com.au",
    rating: "4.2",
    reviewCount: 47,
    status: "new" as const,
    score: "hot" as const,
    tags: [],
    painPoints: [
      "Slow response times mentioned in 3 reviews",
      "Communication gaps with families",
    ],
  },
  {
    name: "Sunshine Physiotherapy",
    googlePlaceId: "ChIJ_seed_sunshine_physio",
    category: "Physiotherapist",
    address: "45 Hampshire Rd",
    suburb: "Sunshine",
    state: "VIC",
    postcode: "3020",
    country: "AU",
    lat: -37.788,
    lng: 144.833,
    phone: "03 9311 2200",
    website: "sunshinephysio.com.au",
    email: "admin@sunshinephysio.com.au",
    rating: "4.7",
    reviewCount: 123,
    status: "qualified" as const,
    score: "warm" as const,
    tags: [],
    painPoints: [
      "Parking difficulties noted",
      "Wait times for appointments",
    ],
  },
  {
    name: "Western Disability Services",
    googlePlaceId: "ChIJ_seed_western_disability",
    category: "NDIS Provider",
    address: "88 Watton St",
    suburb: "Werribee",
    state: "VIC",
    postcode: "3030",
    country: "AU",
    lat: -37.899,
    lng: 144.661,
    phone: "03 9741 0001",
    website: null,
    email: null,
    rating: "3.8",
    reviewCount: 31,
    status: "new" as const,
    score: "hot" as const,
    tags: [],
    painPoints: [
      "No website presence",
      "Invoicing delays mentioned twice",
      "Staff turnover concerns",
    ],
  },
  {
    name: "CareConnect Allied Health",
    googlePlaceId: "ChIJ_seed_careconnect",
    category: "Allied Health",
    address: "12 High St",
    suburb: "Melton",
    state: "VIC",
    postcode: "3337",
    country: "AU",
    lat: -37.683,
    lng: 144.578,
    phone: "03 9747 8800",
    website: "careconnect.com.au",
    email: "hello@careconnect.com.au",
    rating: "4.5",
    reviewCount: 89,
    status: "contacted" as const,
    score: "warm" as const,
    tags: [],
    painPoints: [
      "Limited weekend availability",
      "Booking system outdated",
    ],
  },
  {
    name: "Bayside Support Coordination",
    googlePlaceId: "ChIJ_seed_bayside_support",
    category: "Support Coordinator",
    address: "7 Church St",
    suburb: "Brighton",
    state: "VIC",
    postcode: "3186",
    country: "AU",
    lat: -37.906,
    lng: 144.987,
    phone: "03 9596 1100",
    website: "baysidesupport.com.au",
    email: "team@baysidesupport.com.au",
    rating: "4.9",
    reviewCount: 67,
    status: "proposal" as const,
    score: "hot" as const,
    tags: [],
    painPoints: [
      "Growing fast, may need better systems",
    ],
  },
  {
    name: "Northern Community Care",
    googlePlaceId: "ChIJ_seed_northern_cc",
    category: "NDIS Provider",
    address: "200 Broadway",
    suburb: "Reservoir",
    state: "VIC",
    postcode: "3073",
    country: "AU",
    lat: -37.717,
    lng: 145.007,
    phone: "03 9460 5500",
    website: "northerncc.org.au",
    email: "admin@northerncc.org.au",
    rating: "3.5",
    reviewCount: 22,
    status: "new" as const,
    score: "cold" as const,
    tags: [],
    painPoints: [
      "Poor Google presence",
      "Only 22 reviews despite years operating",
    ],
  },
  {
    name: "Yarra Valley OT",
    googlePlaceId: "ChIJ_seed_yarra_valley_ot",
    category: "Occupational Therapist",
    address: "15 Main St",
    suburb: "Lilydale",
    state: "VIC",
    postcode: "3140",
    country: "AU",
    lat: -37.756,
    lng: 145.354,
    phone: "03 9735 2000",
    website: "yarravalleyot.com.au",
    email: "bookings@yarravalleyot.com.au",
    rating: "4.8",
    reviewCount: 156,
    status: "new" as const,
    score: "unscored" as const,
    tags: [],
    painPoints: [],
  },
  {
    name: "Peninsula Plan Management",
    googlePlaceId: "ChIJ_seed_peninsula_pm",
    category: "Plan Manager",
    address: "33 Young St",
    suburb: "Frankston",
    state: "VIC",
    postcode: "3199",
    country: "AU",
    lat: -38.143,
    lng: 145.126,
    phone: "03 9783 9000",
    website: "peninsulapm.com.au",
    email: "plans@peninsulapm.com.au",
    rating: "4.1",
    reviewCount: 38,
    status: "new" as const,
    score: "warm" as const,
    tags: [],
    painPoints: [
      "Invoice processing delays",
      "Participant portal is confusing",
    ],
  },
  {
    name: "Dandenong Ranges Therapy",
    googlePlaceId: "ChIJ_seed_dandenong_therapy",
    category: "Allied Health",
    address: "5 Belgrave Rd",
    suburb: "Belgrave",
    state: "VIC",
    postcode: "3160",
    country: "AU",
    lat: -37.909,
    lng: 145.354,
    phone: "03 9754 1200",
    website: "drtherapy.com.au",
    email: null,
    rating: "4.6",
    reviewCount: 71,
    status: "new" as const,
    score: "unscored" as const,
    tags: [],
    painPoints: [
      "No email found on website",
    ],
  },
  {
    name: "Geelong Disability Network",
    googlePlaceId: "ChIJ_seed_geelong_dn",
    category: "NDIS Provider",
    address: "100 Moorabool St",
    suburb: "Geelong",
    state: "VIC",
    postcode: "3220",
    country: "AU",
    lat: -38.147,
    lng: 144.361,
    phone: "03 5222 4000",
    website: "gdnetwork.com.au",
    email: "contact@gdnetwork.com.au",
    rating: "3.9",
    reviewCount: 55,
    status: "rejected" as const,
    score: "cold" as const,
    tags: [],
    painPoints: [
      "Multiple complaints about billing",
      "Staff not returning calls",
    ],
  },
] as const;

/** Flat lead type derived from seed data (for component use before DB wiring) */
export type SeedLead = (typeof SEED_LEADS)[number];
